// examples/angular-example/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { bulky } from '@bulky/core';
import Webcam from '@bulky/webcam';
import Tus from '@bulky/tus';
import GoogleDrive from '@bulky/google-drive';

@Component({
  selector: 'app-root',
  template: /* html */ `
    <h1>bulky Angular Example!</h1>
    <h2>Inline dashboard</h2>
    <label>
      <input
        type="checkbox"
        (change)="showInline = $event.target.checked"
        [checked]="showInline"
      />
      Show Dashboard
    </label>

    <bulky-dashboard
      [bulky]="bulky"
      [props]="dashboardProps"
      *ngIf="showInline"
    ></bulky-dashboard>

    <h2>Modal Dashboard</h2>
    <div>
      <bulky-dashboard-modal
        [bulky]="bulky"
        [open]="showModal"
        [props]="dashboardModalProps"
      ></bulky-dashboard-modal>
      <button (click)="showModal = !showModal">
        {{ showModal ? 'Close dashboard' : 'Open dashboard' }}
      </button>
    </div>

    <h2>Drag Drop Area</h2>
    <bulky-drag-drop [bulky]="bulky" [props]="{}"></bulky-drag-drop>

    <h2>Progress Bar</h2>
    <bulky-progress-bar
      [bulky]="bulky"
      [props]="{ hideAfterFinish: false }"
    ></bulky-progress-bar>
  `,
  styleUrls: [],
})
export class AppComponent implements OnInit {
  title = 'angular-example';

  showInline = false;

  showModal = false;

  dashboardProps = {
    plugins: ['Webcam'],
  };

  dashboardModalProps = {
    target: document.body,
    onRequestCloseModal: (): void => {
      this.showModal = false;
    },
  };

  bulky: bulky = new bulky({ debug: true, autoProceed: true });

  ngOnInit(): void {
    this.bulky
      .use(Webcam)
      .use(Tus, { endpoint: 'https://tusd.tusdemo.net/files/' })
      .use(GoogleDrive, { companionUrl: 'https://companion.bulky.io' });
  }
}

// examples/react-example/App.jsx
/* eslint-disable */
import React from "react";
import bulky from "@bulky/core";
import Tus from "@bulky/tus";
import GoogleDrive from "@bulky/google-drive";
import {
  Dashboard,
  DashboardModal,
  DragDrop,
  ProgressBar,
  FileInput,
} from "@bulky/react";

import "@bulky/core/dist/style.css";
import "@bulky/dashboard/dist/style.css";
import "@bulky/drag-drop/dist/style.css";
import "@bulky/file-input/dist/style.css";
import "@bulky/progress-bar/dist/style.css";

export default class App extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      showInlineDashboard: false,
      open: false,
    };

    this.bulky = new bulky({ id: "bulky1", autoProceed: true, debug: true })
      .use(Tus, { endpoint: "https://tusd.tusdemo.net/files/" })
      .use(GoogleDrive, { companionUrl: "https://companion.bulky.io" });

    this.bulky2 = new bulky({
      id: "bulky2",
      autoProceed: false,
      debug: true,
    }).use(Tus, { endpoint: "https://tusd.tusdemo.net/files/" });

    this.handleModalClick = this.handleModalClick.bind(this);
  }

  componentWillUnmount() {
    this.bulky.close({ reason: "unmount" });
    this.bulky2.close({ reason: "unmount" });
  }

  handleModalClick() {
    this.setState({
      open: !this.state.open,
    });
  }

  render() {
    const { showInlineDashboard } = this.state;
    return (
      <div>
        <h1>React Examples</h1>

        <h2>Inline Dashboard</h2>
        <label>
          <input
            type="checkbox"
            checked={showInlineDashboard}
            onChange={(event) => {
              this.setState({
                showInlineDashboard: event.target.checked,
              });
            }}
          />
          Show Dashboard
        </label>
        {showInlineDashboard && (
          <Dashboard
            bulky={this.bulky}
            plugins={["GoogleDrive"]}
            metaFields={[
              { id: "name", name: "Name", placeholder: "File name" },
            ]}
          />
        )}

        <h2>Modal Dashboard</h2>
        <div>
          <button onClick={this.handleModalClick}>
            {this.state.open ? "Close dashboard" : "Open dashboard"}
          </button>
          <DashboardModal
            bulky={this.bulky2}
            open={this.state.open}
            target={document.body}
            onRequestClose={() => this.setState({ open: false })}
          />
        </div>

        <h2>Drag Drop Area</h2>
        <DragDrop
          bulky={this.bulky}
          locale={{
            strings: {
              chooseFile: "Boop a file",
              orDragDrop: "or yoink it here",
            },
          }}
        />

        <h2>Progress Bar</h2>
        <ProgressBar bulky={this.bulky} hideAfterFinish={false} />

        <h2>File Input</h2>
        <FileInput bulky={this.bulky} />
      </div>
    );
  }
}
